--- #YAML:1.0
name:                iTunes-Sid
version:             0.41
abstract:            iTunes SC Info.sidx common user database manipulation
license:             Other
author:              
    - William Hererra (whererra@skylightview.com)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Audio::M4P::Atom:              0.4
    Carp:                          0
    Crypt::AppleTwoFish:           0.05
    Crypt::Rijndael:               0
    Digest::MD5:                   0
    File::Basename:                0
    File::Find::Rule:              0
    File::Path:                    0
    List::Util:                    0
    Math::BigInt:                  0
    Scalar::Util:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
